import { CircleDot, FolderKanban, BookOpen, GitBranch, Clock3, Filter, Search, Layers3, FileSearch, Sparkles, ShieldCheck } from "lucide-react";

export function WorkspaceMockup({ compact = false }: { compact?: boolean }) {
  return <div className={`workspace-shell ${compact ? "compact" : ""}`}>
    <div className="workspace-top"><div className="window-dots"><i /><i /><i /></div><span>ORVENE / RESEARCH OS</span><span className="workspace-status"><span className="status-dot" />All systems clear</span></div>
    <div className="workspace-body"><aside className="workspace-sidebar"><div className="side-logo"><span className="logo-mark"><CircleDot size={12} /></span>orvene</div><p className="side-section">Workspace</p><div className="side-item selected"><FolderKanban size={14} /> Research registry <b>12</b></div><div className="side-item"><BookOpen size={14} /> Source library <b>84</b></div><div className="side-item"><GitBranch size={14} /> Findings <b>28</b></div><div className="side-item"><Clock3 size={14} /> Activity history</div><p className="side-section">Your spaces</p><div className="side-item muted">+ New research space</div></aside>
      <main className="workspace-main"><div className="workspace-heading"><div><span className="tiny-label">Tuesday, 08 October 2026</span><h3>Good morning, Maya</h3></div><div className="avatar">MC</div></div><div className="workspace-toolbar"><div className="search-field"><Search size={14} />Search workspace</div><button><Filter size={14} /> Filters</button><button>+ New project</button></div><div className="workspace-metrics"><div><span>Active research</span><strong>12</strong><small>Across 4 teams</small></div><div><span>Pending review</span><strong>07</strong><small className="amber">Needs attention</small></div><div><span>New findings</span><strong>28</strong><small className="green">+6 this week</small></div></div><div className="workspace-panels"><div className="panel project-panel"><div className="panel-title"><span>Active research projects</span><a href="#features">View all</a></div>{[[ "Carbon capture pathways","R&D / Materials","In progress","68%" ],["Synthetic biology landscape","Strategy / Emerging tech","In review","84%"],["Industrial AI adoption","Market intelligence","Scoping","24%"]].map(([title, team, status, progress]) => <div className="project-row" key={title}><div className="project-icon"><Layers3 size={15} /></div><div className="project-info"><strong>{title}</strong><span>{team}</span></div><span className="pill">{status}</span><div className="progress"><i style={{ width: progress }} /></div></div>)}</div><div className="panel activity-panel"><div className="panel-title"><span>Recent activity</span><a href="#features">Open log</a></div><div className="activity-item"><span className="activity-icon blue"><FileSearch size={13} /></span><div><strong>New source registered</strong><span>MIT Energy Initiative � 12m</span></div></div><div className="activity-item"><span className="activity-icon peach"><Sparkles size={13} /></span><div><strong>Finding ready for review</strong><span>Carbon capture pathways � 1h</span></div></div><div className="activity-item"><span className="activity-icon green"><ShieldCheck size={13} /></span><div><strong>Evidence validated</strong><span>Synthetic biology � 3h</span></div></div></div></div></main></div>
  </div>;
}

