export type LegalSection = { no: string; heading: string; paragraphs?: string[]; bullets?: string[] };
export type LegalDoc = { slug: string; eyebrow: string; title: string; lede: string; updated: string; sections: LegalSection[] };

export const terms: LegalDoc = {
  slug: 'terms',
  eyebrow: 'LEGAL / TERMS OF SERVICE',
  title: 'Terms of Service',
  lede: 'The agreement between you and Orvene when you use our research and discovery platform.',
  updated: 'Effective 2 October 2026',
  sections: [
    { no: '01', heading: 'Agreement and eligibility', paragraphs: ['These Terms of Service ("Terms") govern your access to and use of the Orvene platform, websites, and related services (the "Service"). By creating an account, purchasing a plan, or simply using the Service, you agree to these Terms.', 'You must be at least 18 years old and able to enter into a binding contract. If you are accepting on behalf of an organisation, you confirm that you have the authority to bind that organisation.'] },
    { no: '02', heading: 'Accounts and access', bullets: ['You are responsible for the accuracy of your account details and for keeping your credentials confidential.', 'Tell us promptly if you suspect unauthorised access to your account.', 'Team plan seats are managed by your workspace owner, who can add or remove access at any time.', 'You are responsible for all activity that happens under your account, including activity by people you invite.'] },
    { no: '03', heading: 'Acceptable use', paragraphs: ['You agree to use the Service only for lawful research and knowledge work. In particular you must not:', ], bullets: ['Scrape, crawl, copy, or bulk-extract any part of the Service, or attempt to reverse engineer it beyond what applicable law permits.', 'Upload material that is unlawful, infringing, or that you do not have the right to share.', 'Probe, overload, disrupt, or gain unauthorised access to the Service or its infrastructure.', 'Resell, sublicense, or white-label the Service without our written permission.', 'Rely on automated outputs to make decisions about people without appropriate human review.'] },
    { no: '04', heading: 'Your content', paragraphs: ['You keep all rights to the material you upload — sources, notes, findings, and other content ("Your Content").', 'You grant us a worldwide, non-exclusive, royalty-free licence to host, copy, transmit, and display Your Content only as necessary to operate, secure, and improve the Service for you.', 'You confirm that you hold the rights and permissions required to share Your Content with us.'] },
    { no: '05', heading: 'Research outputs are aids, not advice', paragraphs: ['Orvene is built to make research organised, traceable, and reusable. It does not replace professional judgement. Summaries, findings, comparisons, and any AI-assisted output are research aids — they are not legal, medical, financial, safety, or engineering advice.', 'You are responsible for reviewing the underlying sources and evidence, and for verifying any conclusion before relying on it or acting on it.'] },
    { no: '06', heading: 'Plans, fees, and payments', paragraphs: ['Team and Business plans are purchased as one-time payments. Prices are shown on our pricing page and confirmed in the PayPal checkout window before you authorise anything.', 'Payments are processed by PayPal. We never see or store your card details. Taxes, where applicable, are added at checkout.', 'Where a payment fails, plan access may be suspended until payment is resolved. Enterprise customers may be governed by a separate order form, which takes precedence over these Terms.'] },
    { no: '07', heading: 'Refunds and cancellation', paragraphs: ['Plans are one-time purchases rather than subscriptions. If the Service was materially unavailable to you during the period following your purchase, contact hello@orvene.net within 14 days and we will review a refund.', 'Because research histories and evidence trails take time to build, we cannot refund a workspace that has been actively used for research.'] },
    { no: '08', heading: 'Third-party services', paragraphs: ['The Service relies on third parties for some functions, including payment processing (PayPal), bot protection (Cloudflare Turnstile), contact form delivery (Formspree), and optional live chat (Tawk.to). Their own terms and privacy policies apply to your use of those services.', 'Links to third-party sites are provided for convenience. We do not control and are not responsible for their content.'] },
    { no: '09', heading: 'Confidentiality and security', paragraphs: ['We treat your research data as confidential and take reasonable technical and organisational measures to protect it. We may use aggregated, de-identified information to understand how the Service performs.', 'No system is perfectly secure. If you believe your data has been compromised, contact security@orvene.net as soon as possible.'] },
    { no: '10', heading: 'Intellectual property', paragraphs: ['The Service — including its software, design, brand, and documentation — belongs to Orvene and its licensors. We do not claim ownership of Your Content or of the findings you produce.', 'If you choose to send us feedback, you grant us a non-exclusive licence to use it without restriction or attribution.'] },
    { no: '11', heading: 'Third-party claims', paragraphs: ['You agree to indemnify and hold harmless Orvene from any claim by a third party arising from Your Content, your use of the Service in breach of these Terms, or your misuse of research outputs.'] },
    { no: '12', heading: 'Warranties', paragraphs: ['The Service is provided "as is" and "as available". To the fullest extent permitted by law, we disclaim all implied warranties, including merchantability, fitness for a particular purpose, accuracy, and non-infringement. We do not warrant that the Service will be uninterrupted, error-free, or that outputs will be complete or correct.'] },
    { no: '13', heading: 'Limitation of liability', paragraphs: ['To the fullest extent permitted by law, Orvene is not liable for indirect, incidental, special, or consequential loss, or for loss of data, profits, revenue, or goodwill, arising from your use of the Service.', 'Our total aggregate liability for any claim is limited to the greater of the amount you paid us in the 12 months before the claim, or 100 USD. Nothing in these Terms excludes liability that cannot be excluded by law, including for death, personal injury, or fraud.'] },
    { no: '14', heading: 'Suspension and termination', paragraphs: ['You may stop using the Service at any time. We may suspend or terminate access if you breach these Terms, create a security risk to the platform or other customers, or are required to do so by law.', 'On termination you can export your workspace content for 30 days, after which we delete it in line with our Privacy Policy.'] },
    { no: '15', heading: 'Changes to these Terms', paragraphs: ['We may update these Terms as the Service evolves. Material changes will be announced in the product or by email at least 30 days before they take effect. Continuing to use the Service after that date means you accept the revised Terms.'] },
    { no: '16', heading: 'Governing law and disputes', paragraphs: ['These Terms are governed by the laws of [JURISDICTION], without regard to conflict-of-law rules. Before starting proceedings, both parties agree to attempt good-faith negotiation for 30 days. Disputes that remain unresolved are subject to the exclusive jurisdiction of the courts of [JURISDICTION].'] },
    { no: '17', heading: 'Contact', paragraphs: ['Questions about these Terms: hello@orvene.net', '[COMPANY LEGAL NAME], [REGISTERED ADDRESS]'] },
  ],
};

export const privacy: LegalDoc = {
  slug: 'privacy',
  eyebrow: 'LEGAL / PRIVACY POLICY',
  title: 'Privacy Policy',
  lede: 'What we collect, why we collect it, and the choices you control.',
  updated: 'Effective 2 October 2026',
  sections: [
    { no: '01', heading: 'Who we are', paragraphs: ['Orvene ("we", "us") operates a research and discovery platform. For the purposes of data protection law we are the controller of the personal data described in this policy.', 'If you have a question about this policy or our data practices, contact privacy@orvene.net.'] },
    { no: '02', heading: 'Information we collect', bullets: ['Information you give us: the name, work email, organisation, inquiry type, and message you submit through the contact form, plus any account details you provide if you sign up.', 'Technical data: IP address, device and browser type, pages viewed, referrer, and timestamps recorded in server logs.', 'Cookies and preferences: your cookie choice (see section 04), plus security cookies set when you submit a form.', 'Payment information: payments are handled entirely by PayPal. We receive the amount, currency, and transaction reference — never your full card number.', 'Support conversations: messages you send us through live chat or email.'] },
    { no: '03', heading: 'How we use your information', bullets: ['To respond to your inquiry, provide the Service, and support your workspace.', 'To keep the Service secure, prevent abuse, and enforce our Terms.', 'To understand which parts of the site are useful — only where you have given consent for analytics.', 'To send transactional service messages (receipts, security alerts). We do not send marketing email unless you opt in.', 'To meet legal, tax, and accounting obligations.'] },
    { no: '04', heading: 'Cookies and similar technologies', paragraphs: ['We keep the number of cookies small and their purpose clear:', 'You can change or withdraw your choice at any time using the "Cookie settings" link in the footer. Blocking essential cookies may prevent the contact form from working.'], bullets: ['Essential (always active): your cookie preference, Cloudflare Turnstile bot-protection cookies (short-lived, set when you submit the contact form), and security cookies required to deliver the site.', 'Analytics and live chat (optional, only with your consent): Tawk.to live chat and any analytics tooling we choose to enable.'] },
    { no: '05', heading: 'Legal bases', bullets: ['Performance of our contract with you — running the Service, storing your workspace, responding to inquiries.', 'Consent — analytics and live chat cookies, and non-essential technologies.', 'Legitimate interests — security, fraud prevention, and service reliability, balanced against your rights.', 'Legal obligation — retaining records where the law requires it.'] },
    { no: '06', heading: 'Who we share it with', paragraphs: ['We do not sell or rent your personal data, and we do not share it for cross-context behavioural advertising. We may disclose information where required by law or to protect the rights and safety of Orvene, our customers, or the public.'], bullets: ['Cloudflare — hosting security and Turnstile bot protection.', 'Formspree — delivering contact form submissions to our inbox.', 'PayPal — processing payments.', 'Tawk.to — live chat, only where you have consented to it.', 'Our hosting, storage, and email providers, who process data on our instructions.'] },
    { no: '07', heading: 'How long we keep it', bullets: ['Contact form inquiries: up to 24 months from your last message.', 'Account and workspace content: while your account is active, then 90 days before deletion.', 'Server and security logs: up to 12 months.', 'Live chat transcripts: up to 24 months.', 'Billing records: as long as tax and accounting law requires.'] },
    { no: '08', heading: 'Security', paragraphs: ['We use encryption in transit, access controls, and least-privilege practices to protect your data. No method of transmission or storage is completely secure.', 'If you believe your data has been exposed, contact security@orvene.net.'] },
    { no: '09', heading: 'International transfers', paragraphs: ['Some of our providers process data outside your country of residence. Where they do, we rely on recognised safeguards such as adequacy decisions or standard contractual clauses.'] },
    { no: '10', heading: 'Your rights', paragraphs: ['Email privacy@orvene.net and we will respond within 30 days. California residents also have the rights described in the CCPA/CPRA, including the right to opt out of sale or sharing; Orvene does not sell or share personal data as those terms are defined.'], bullets: ['Access — ask what personal data we hold about you and get a copy.', 'Correction — ask us to fix inaccurate or incomplete data.', 'Deletion — ask us to delete your data.', 'Restriction or portability — limit how we use it, or receive it in a portable format.', 'Objection — object to processing based on legitimate interests.', 'Withdraw consent — change your mind about analytics or live chat at any time via "Cookie settings".', 'Complaint — raise a concern with your local data protection authority.'] },
    { no: '11', heading: 'Children', paragraphs: ['The Service is not directed at children under 16, and we do not knowingly collect personal data from them. If you believe a child has provided us data, contact privacy@orvene.net and we will delete it.'] },
    { no: '12', heading: 'Changes to this policy', paragraphs: ['We may update this policy as the Service or the law changes. Material changes will be announced in the product or by email, and the "Effective" date at the top will be updated.'] },
    { no: '13', heading: 'Contact', paragraphs: ['[COMPANY LEGAL NAME], [REGISTERED ADDRESS]', 'Privacy questions: privacy@orvene.net · Security: security@orvene.net'] },
  ],
};